version: '3.7'

services:

  grpc:
    container_name: "grpc"
    working_dir: /app
    ports:
      - 8080:8080
    command: ["sh","./wait.sh"]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
